#!/bin/bash

set -e -x

export GOPATH=$PWD/gopath

export GOARCH=amd64

pkg=github.com/sapcc/lyra-cli
date +%Y%m%d%H%M%S > build-darwin/version
gitcommit=$(git -C gopath/src/$pkg rev-parse --short HEAD)
ldflags="-s -w"
ldflags="$ldflags -X $pkg/version.Version=$(cat build-darwin/version)"
ldflags="$ldflags -X $pkg/version.GITCOMMIT=$gitcommit"

go build -o build-darwin/lyra_darwin      -ldflags "$ldflags" $pkg
