#!/bin/bash

set -e -x

export GOPATH=$PWD/gopath

#inject SAP Global Root CA into nocgo darwin trust store
sed '/roots.AppendCertsFromPEM(data)/r '<(echo "roots.AppendCertsFromPEM([]byte(\`$(cat /etc/ssl/certs/SAP_Global_Root.pem)\`))") -i /usr/local/go/src/crypto/x509/root_darwin.go

export GOARCH=amd64

apt-get update && apt-get install -y bzip2
curl -L http://upx.sourceforge.net/download/upx-3.91-amd64_linux.tar.bz2 | tar -C /usr/local/bin -jx --strip-components=1 upx-3.91-amd64_linux/upx

GOOS=linux   go build -o build/lyra_linux       -ldflags "-s -w" github.com/sapcc/lyra-cli
upx build/lyra_linux
GOOS=darwin  go build -o build/lyra_darwin      -ldflags "-s -w" github.com/sapcc/lyra-cli
upx build/lyra_darwin
GOOS=windows go build -o build/lyra_windows.exe -ldflags "-s -w" github.com/sapcc/lyra-cli
upx build/lyra_windows.exe
