#!/bin/bash

set -e -x

version=$(cat cli.version/current)
echo "v$version" > release/name
echo "v$version" > release/tag
git -C cli.git rev-parse HEAD > release/commitish

cat > release/body <<EOF
A release candidate of the lyra cli.
EOF

mkdir release/artifacts
cp binary-*/* release/artifacts/
upx release/artifacts/*
