#!/bin/bash

set -e -x
export GOPATH=$PWD/gopath
PKG=github.com/sapcc/lyra-cli

packages_to_test=$(go list -f '{{ join .Deps "\n" }}' $PKG | grep -v vendor|grep $PKG)

cd $GOPATH/src/$PKG

go test -v $packages_to_test 
